services:
  referee:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx        
    ports:
        - "443:443"
    restart: always
    networks:
        - monabid.42.fr
    depends_on:
        - wordpress
    volumes:
        - wp_files:/var/wordpress
